### ISSUE TITLE
Implement federated learning cycles in PyGrid

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/PyGrid#438]
This ticket will need to be beefed up quite a bit more in the near future. For now, let's think of it as the following:

By this point, we've got plans and protocols hosted on PyGrid successfully (https://github.com/OpenMined/PyGrid/issues/413) and we've got a method to push these plans and protocols from PySyft to PyGrid (https://github.com/OpenMined/PyGrid/issues/435). Now we need to actually write the code that triggers a new federated learning cycle.

This process should roughly incorporate:
- [x] Allowing for workers to submit an inquiry for training on a cycle
- [x] Using the `server_config` parameters, appropriately choose a subsetted pool of workers (#479)
- [x] Allow those workers to download the current model, worker plans, workers protocols, and client config required to run the plan on their device
- [x] Accept an updated model diff from a worker, or in the presence of a protocol, accept a share of the securely aggregated model from a worker. (#468)

At this point, that should roughly define the scope of work. We're going to separate the "averaging" and "global model updating" functionality into its own separate Github issue: https://github.com/OpenMined/PyGrid/issues/439

**Comment by cereallarceny** [comment]
The last PR made great progress but definitely doesn't close this issue. I'm reopening it until we have the final system in place. :)
