### ISSUE TITLE
Add averaging plan and global model updating functionality to PyGrid

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/PyGrid#439]
This ticket will need to be beefed up quite a bit more in the near future. For now, let's think of it as the following:

By this point, we've got federated learning cycles implemented in PyGrid (https://github.com/OpenMined/PyGrid/issues/438). This issues builds on the work in that issue by allowing us to average models received by workers and then update the global model itself. This is probably going to be comprised of the following issues:

- [x] Upon receiving a model diff from a worker that IS NOT part of a protocol, average it using the averaging plan supplied by the model developer back into the global model #498 
- [ ] If the model diff is part of a protocol split with other workers, make sure you have each of the required shares from each worker group, and then average those shares into the final model.
- [ ] Once the cycle has been completed, average the models received from the workers and create a new checkpoint
