### ISSUE TITLE
PyGrid Vanity API

### ISSUE THREAD

**Issue by IonesioJunior** [OpenMined/PyGrid#768]
## Description
Implement vanity API needed by OpenGrid

Checklist:

- [ ]  Domain
    - [x] Users
        - [x] Create User
        - [x] Get User
        - [x] Get Users
        - [x] Delete User
        - [x] Search Users
        - [x] Update User
        - [x] PySyft compatiblity
    - [x] Groups
        - [x] Create Group
        - [x] Get Group
        - [x] Get Groups
        - [x] Delete Group
        - [x] Update Group
        - [x] Delete Group
        - [x] PySyft compatiblity
    - [ ] Roles
        - [x] Create Role
        - [x] Get Role
        - [x] Get Roles
        - [x] Update Role
        - [x] Delete Role
        - [ ] PySyft compability
    - [ ] Association Requests
        - [x] Send Association Request
        - [x] Receive Association Request
        - [x] Respond to Association Request
        - [x] Get Association Request
        - [x] Get Association Requests
        - [x] Delete Association Request
        - [ ] PySyft/Network compatiblity
    - [x] Initial Setup
        - [x] Create Initial Setup
        - [x] Get Initial Setup
        - [x] PySyft Compatibility 
    - [ ] Data Centric
        - [ ] Dataset
            - [ ] Create Dataset
            - [ ] Get Dataset
            - [ ] Get Datasets
            - [ ] Update Dataset
            - [ ] Delete Dataset 
            - [ ] PySyft Compatiblity
        - [x] Tensor
            - [x] Create Tensor
            - [x] Get Tensor
            - [x] Get Tensor
            - [x] Update Tensor
            - [x] Delete Tensor
            - [x] PySyft Compatiblity
        - [ ] Infrastructure
           - [x]  Create Worker
           - [x] Get Worker
           - [x] Get Workers
           - [x] Delete Worker
           - [ ] Cloud Deployment
- [ ] Network

**Comment by IonesioJunior** [comment]
Just adding @tcp  in order to keep him updated about our progress! :)
